version: '3.3'

services:
  zf:
    build: ./zf3
    ports:
     - '8080:80'
    volumes:
     - ./zf3:/var/www
    environment:
      - GOOGLE_KEY_ENV=AIzaSyCBBqggEb7D5vA7F9iB0duDN1nKpBGpBTc
  vue:
    build: ./vue
    ports:
      - '8081:8080'
      - '8000:8000'
    stdin_open: true
    tty: true
    environment:
      - NODE_ENV=development
      - GOOGLE_KEY_ENV=AIzaSyCBBqggEb7D5vA7F9iB0duDN1nKpBGpBTc

networks:
  default:
    driver: bridge
